---
title: "Charles C. Lanfear <br> Curriculum vitae"
#date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: false
    #CDS
    css: ["https://use.fontawesome.com/releases/v5.7.2/css/all.css", "style/one-column-paged.css"]
    #offline
    #css: [one-column.css, "fontawesome-free-5.8.1-web/css/all.css"]
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(stringr)
library(knitr)

publications <- readxl::read_xlsx("../cv_data/publications.xlsx")

cv_entries <- readxl::read_xlsx("../cv_data/cv_entries.xlsx")

```

<div class="grid-container">
<!-- top row -->
```{r summary, child = 'content/summary.Rmd'}
```

```{r contact-info, child = 'content/contact-info.Rmd'}
```
</div>

## Education {.education .nohead .set-width}
```{r, eval= TRUE}
cv_entries %>% 
  arrange(desc(year_begin)) %>%
  filter(type == 'education') %>% 
  mutate(what = str_c(what, ", ", where)) %>% 
  mutate(year_begin = str_replace(year_begin, "In Progress", "Ongoing")) %>%
  # mutate(year = str_c(year_begin, " --- ", year_end)) %>% 
  select(year_begin, what) %>% 
  kable()
```


## Publications {.nohead .publications .set-width}
```{r}
publications_table <- publications %>%
  mutate(year = ifelse(str_detect(year, "Forthcoming"), str_c("9",year),year)) %>%
  arrange(desc(year), authors) %>%
  mutate(year = ifelse(str_detect(year, "Forthcoming"), str_remove(year, "^9"),year)) %>%
  mutate(author_year = str_c(authors, ". ", year, ". ")) %>%
  mutate(title = ifelse(!is.na(url), str_c("[", title, "](", url, ")"), title)) %>% #turn title into link
  mutate(citation = case_when(
    type == "article" ~ str_c(author_year, title, ". ","*", venue,"* ", ifelse(!is.na(issue), issue, "")),
    type == "report" ~ str_c(author_year, title, ". ","*", venue, "*"),
    type == "prep" ~ str_c(authors, ". ", title, ".", ifelse(!is.na(venue), str_c(" In preparation for *",venue,"*"), "")),
    TRUE ~  str_c(authors, ". ", title, ". ", "*", venue,"*"))) %>%
  mutate(citation = str_replace(citation, "CC Lanfear", "**CC Lanfear**"))

publications_table %>%
  filter(type == "article") %>% 
  select(citation) %>%
  knitr::kable()
```

## In Preparation {.nohead .publications .set-width}

```{r}
publications_table %>%
  filter(type == "prep") %>% 
  select(citation) %>%
  knitr::kable()
```

## Reports {.nohead .publications .set-width}

```{r}
publications_table %>%
  filter(type == "report") %>% 
  select(citation) %>%
  knitr::kable()
```

## Courses (Instructor) {.nohead .talks .set-width}
```{r, eval= TRUE}
cv_entries %>% 
  filter(type == 'teaching') %>% 
  mutate(what = ifelse(!is.na(url), str_c("[", what, "](", url, ")"), what)) %>%
  mutate(what = ifelse(!is.na(additional_info), 
    str_c("<span class='work-title'>", what, "</span><br class='work-break'>", where, " - ", additional_info),
    str_c("<span class='work-title'>", what, "</span><br class='work-break'>", where))) %>% 
  mutate(year = ifelse(!is.na(year_end), str_c(year_begin, " --- ", year_end), year_begin)) %>% 
  select(year, what) %>% 
  kable()
```

## Grants and Awards {.nohead .talks .set-width}
```{r, eval= TRUE}
cv_entries %>% 
  arrange(desc(year_begin)) %>%
  filter(type == 'grants_and_awards') %>% 
  mutate(what = str_c(what, ", ", where)) %>% 
  mutate(year = ifelse(!is.na(year_end), str_c(year_begin, " --- ", year_end), year_begin)) %>%
  select(year, what) %>% 
  kable()
```

## Service {.nohead .talks .set-width}
```{r, eval= TRUE}
cv_entries %>% 
  filter(type == 'service') %>% 
  mutate(year_end = ifelse(year_end == "present", "", year_end)) %>% 
  mutate(where = ifelse(!is.na(url), str_c("[", where, "](", url, ")"), where)) %>% 
  mutate(what = str_c(what, ", ", where)) %>%
  mutate(year = case_when( 
           !is.na(year_end) & !is.na(year_begin) ~ str_c(year_begin, " --- ", year_end),
           is.na(year_end) & !is.na(year_begin) ~ year_begin,
           !is.na(year_end) & is.na(year_begin) ~ year_end,
           TRUE ~ "ERROR"
           )) %>% 
  mutate(year_begin = ifelse(is.na(year_begin), year_end, year_begin)) %>%
  arrange(desc(year_begin)) %>%
  select(year, what) %>% 
  kable()
```
